/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SeekersRouteImport } from './routes/seekers'
import { Route as RentVerdictRouteImport } from './routes/rent-verdict'
import { Route as ReferRouteImport } from './routes/refer'
import { Route as PersonaQuizRouteImport } from './routes/persona-quiz'
import { Route as MapRouteImport } from './routes/map'
import { Route as ListingsRouteImport } from './routes/listings'
import { Route as GharpayyRouteImport } from './routes/gharpayy'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as AreasRouteImport } from './routes/areas'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SocietySlugRouteImport } from './routes/society.$slug'
import { Route as PersonaIdRouteImport } from './routes/persona.$id'
import { Route as AreaSlugRouteImport } from './routes/area.$slug'
import { Route as AppSplatRouteImport } from './routes/app.$'
import { Route as GharpayyAreaSlugRouteImport } from './routes/gharpayy.area.$slug'
import { Route as ApiPublicRefreshInsightsRouteImport } from './routes/api/public/refresh-insights'
import { Route as ApiPublicInsightsJsonRouteImport } from './routes/api/public/insights.json'

const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SeekersRoute = SeekersRouteImport.update({
  id: '/seekers',
  path: '/seekers',
  getParentRoute: () => rootRouteImport,
} as any)
const RentVerdictRoute = RentVerdictRouteImport.update({
  id: '/rent-verdict',
  path: '/rent-verdict',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferRoute = ReferRouteImport.update({
  id: '/refer',
  path: '/refer',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonaQuizRoute = PersonaQuizRouteImport.update({
  id: '/persona-quiz',
  path: '/persona-quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsRoute = ListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => rootRouteImport,
} as any)
const GharpayyRoute = GharpayyRouteImport.update({
  id: '/gharpayy',
  path: '/gharpayy',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasRoute = AreasRouteImport.update({
  id: '/areas',
  path: '/areas',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SocietySlugRoute = SocietySlugRouteImport.update({
  id: '/society/$slug',
  path: '/society/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonaIdRoute = PersonaIdRouteImport.update({
  id: '/persona/$id',
  path: '/persona/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AreaSlugRoute = AreaSlugRouteImport.update({
  id: '/area/$slug',
  path: '/area/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSplatRoute = AppSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AppRoute,
} as any)
const GharpayyAreaSlugRoute = GharpayyAreaSlugRouteImport.update({
  id: '/area/$slug',
  path: '/area/$slug',
  getParentRoute: () => GharpayyRoute,
} as any)
const ApiPublicRefreshInsightsRoute =
  ApiPublicRefreshInsightsRouteImport.update({
    id: '/api/public/refresh-insights',
    path: '/api/public/refresh-insights',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicInsightsJsonRoute = ApiPublicInsightsJsonRouteImport.update({
  id: '/api/public/insights/json',
  path: '/api/public/insights/json',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/areas': typeof AreasRoute
  '/compare': typeof CompareRoute
  '/gharpayy': typeof GharpayyRouteWithChildren
  '/listings': typeof ListingsRoute
  '/map': typeof MapRoute
  '/persona-quiz': typeof PersonaQuizRoute
  '/refer': typeof ReferRoute
  '/rent-verdict': typeof RentVerdictRoute
  '/seekers': typeof SeekersRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tools': typeof ToolsRoute
  '/app/$': typeof AppSplatRoute
  '/area/$slug': typeof AreaSlugRoute
  '/persona/$id': typeof PersonaIdRoute
  '/society/$slug': typeof SocietySlugRoute
  '/api/public/refresh-insights': typeof ApiPublicRefreshInsightsRoute
  '/gharpayy/area/$slug': typeof GharpayyAreaSlugRoute
  '/api/public/insights/json': typeof ApiPublicInsightsJsonRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/areas': typeof AreasRoute
  '/compare': typeof CompareRoute
  '/gharpayy': typeof GharpayyRouteWithChildren
  '/listings': typeof ListingsRoute
  '/map': typeof MapRoute
  '/persona-quiz': typeof PersonaQuizRoute
  '/refer': typeof ReferRoute
  '/rent-verdict': typeof RentVerdictRoute
  '/seekers': typeof SeekersRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tools': typeof ToolsRoute
  '/app/$': typeof AppSplatRoute
  '/area/$slug': typeof AreaSlugRoute
  '/persona/$id': typeof PersonaIdRoute
  '/society/$slug': typeof SocietySlugRoute
  '/api/public/refresh-insights': typeof ApiPublicRefreshInsightsRoute
  '/gharpayy/area/$slug': typeof GharpayyAreaSlugRoute
  '/api/public/insights/json': typeof ApiPublicInsightsJsonRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/areas': typeof AreasRoute
  '/compare': typeof CompareRoute
  '/gharpayy': typeof GharpayyRouteWithChildren
  '/listings': typeof ListingsRoute
  '/map': typeof MapRoute
  '/persona-quiz': typeof PersonaQuizRoute
  '/refer': typeof ReferRoute
  '/rent-verdict': typeof RentVerdictRoute
  '/seekers': typeof SeekersRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tools': typeof ToolsRoute
  '/app/$': typeof AppSplatRoute
  '/area/$slug': typeof AreaSlugRoute
  '/persona/$id': typeof PersonaIdRoute
  '/society/$slug': typeof SocietySlugRoute
  '/api/public/refresh-insights': typeof ApiPublicRefreshInsightsRoute
  '/gharpayy/area/$slug': typeof GharpayyAreaSlugRoute
  '/api/public/insights/json': typeof ApiPublicInsightsJsonRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/areas'
    | '/compare'
    | '/gharpayy'
    | '/listings'
    | '/map'
    | '/persona-quiz'
    | '/refer'
    | '/rent-verdict'
    | '/seekers'
    | '/sitemap.xml'
    | '/tools'
    | '/app/$'
    | '/area/$slug'
    | '/persona/$id'
    | '/society/$slug'
    | '/api/public/refresh-insights'
    | '/gharpayy/area/$slug'
    | '/api/public/insights/json'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/areas'
    | '/compare'
    | '/gharpayy'
    | '/listings'
    | '/map'
    | '/persona-quiz'
    | '/refer'
    | '/rent-verdict'
    | '/seekers'
    | '/sitemap.xml'
    | '/tools'
    | '/app/$'
    | '/area/$slug'
    | '/persona/$id'
    | '/society/$slug'
    | '/api/public/refresh-insights'
    | '/gharpayy/area/$slug'
    | '/api/public/insights/json'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/areas'
    | '/compare'
    | '/gharpayy'
    | '/listings'
    | '/map'
    | '/persona-quiz'
    | '/refer'
    | '/rent-verdict'
    | '/seekers'
    | '/sitemap.xml'
    | '/tools'
    | '/app/$'
    | '/area/$slug'
    | '/persona/$id'
    | '/society/$slug'
    | '/api/public/refresh-insights'
    | '/gharpayy/area/$slug'
    | '/api/public/insights/json'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AreasRoute: typeof AreasRoute
  CompareRoute: typeof CompareRoute
  GharpayyRoute: typeof GharpayyRouteWithChildren
  ListingsRoute: typeof ListingsRoute
  MapRoute: typeof MapRoute
  PersonaQuizRoute: typeof PersonaQuizRoute
  ReferRoute: typeof ReferRoute
  RentVerdictRoute: typeof RentVerdictRoute
  SeekersRoute: typeof SeekersRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ToolsRoute: typeof ToolsRoute
  AreaSlugRoute: typeof AreaSlugRoute
  PersonaIdRoute: typeof PersonaIdRoute
  SocietySlugRoute: typeof SocietySlugRoute
  ApiPublicRefreshInsightsRoute: typeof ApiPublicRefreshInsightsRoute
  ApiPublicInsightsJsonRoute: typeof ApiPublicInsightsJsonRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seekers': {
      id: '/seekers'
      path: '/seekers'
      fullPath: '/seekers'
      preLoaderRoute: typeof SeekersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rent-verdict': {
      id: '/rent-verdict'
      path: '/rent-verdict'
      fullPath: '/rent-verdict'
      preLoaderRoute: typeof RentVerdictRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refer': {
      id: '/refer'
      path: '/refer'
      fullPath: '/refer'
      preLoaderRoute: typeof ReferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/persona-quiz': {
      id: '/persona-quiz'
      path: '/persona-quiz'
      fullPath: '/persona-quiz'
      preLoaderRoute: typeof PersonaQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings': {
      id: '/listings'
      path: '/listings'
      fullPath: '/listings'
      preLoaderRoute: typeof ListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gharpayy': {
      id: '/gharpayy'
      path: '/gharpayy'
      fullPath: '/gharpayy'
      preLoaderRoute: typeof GharpayyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas': {
      id: '/areas'
      path: '/areas'
      fullPath: '/areas'
      preLoaderRoute: typeof AreasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/society/$slug': {
      id: '/society/$slug'
      path: '/society/$slug'
      fullPath: '/society/$slug'
      preLoaderRoute: typeof SocietySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/persona/$id': {
      id: '/persona/$id'
      path: '/persona/$id'
      fullPath: '/persona/$id'
      preLoaderRoute: typeof PersonaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/area/$slug': {
      id: '/area/$slug'
      path: '/area/$slug'
      fullPath: '/area/$slug'
      preLoaderRoute: typeof AreaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$': {
      id: '/app/$'
      path: '/$'
      fullPath: '/app/$'
      preLoaderRoute: typeof AppSplatRouteImport
      parentRoute: typeof AppRoute
    }
    '/gharpayy/area/$slug': {
      id: '/gharpayy/area/$slug'
      path: '/area/$slug'
      fullPath: '/gharpayy/area/$slug'
      preLoaderRoute: typeof GharpayyAreaSlugRouteImport
      parentRoute: typeof GharpayyRoute
    }
    '/api/public/refresh-insights': {
      id: '/api/public/refresh-insights'
      path: '/api/public/refresh-insights'
      fullPath: '/api/public/refresh-insights'
      preLoaderRoute: typeof ApiPublicRefreshInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/insights/json': {
      id: '/api/public/insights/json'
      path: '/api/public/insights/json'
      fullPath: '/api/public/insights/json'
      preLoaderRoute: typeof ApiPublicInsightsJsonRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppSplatRoute: typeof AppSplatRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSplatRoute: AppSplatRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface GharpayyRouteChildren {
  GharpayyAreaSlugRoute: typeof GharpayyAreaSlugRoute
}

const GharpayyRouteChildren: GharpayyRouteChildren = {
  GharpayyAreaSlugRoute: GharpayyAreaSlugRoute,
}

const GharpayyRouteWithChildren = GharpayyRoute._addFileChildren(
  GharpayyRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AreasRoute: AreasRoute,
  CompareRoute: CompareRoute,
  GharpayyRoute: GharpayyRouteWithChildren,
  ListingsRoute: ListingsRoute,
  MapRoute: MapRoute,
  PersonaQuizRoute: PersonaQuizRoute,
  ReferRoute: ReferRoute,
  RentVerdictRoute: RentVerdictRoute,
  SeekersRoute: SeekersRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ToolsRoute: ToolsRoute,
  AreaSlugRoute: AreaSlugRoute,
  PersonaIdRoute: PersonaIdRoute,
  SocietySlugRoute: SocietySlugRoute,
  ApiPublicRefreshInsightsRoute: ApiPublicRefreshInsightsRoute,
  ApiPublicInsightsJsonRoute: ApiPublicInsightsJsonRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
