// @ts-nocheck
/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Gharpayy Super App API · Referral + CLaaS + PG Marketplace
 * OpenAPI spec version: 0.2.0
 */
export interface HealthStatus {
  status: string;
}

export interface ErrorResponse {
  error: string;
  message: string;
}

export interface SuccessResponse {
  success: boolean;
  message: string;
}

export type RegisterReferrerBodyPersona =
  (typeof RegisterReferrerBodyPersona)[keyof typeof RegisterReferrerBodyPersona];

export const RegisterReferrerBodyPersona = {
  EARNER: "EARNER",
  STUDENT: "STUDENT",
  GUARD: "GUARD",
  PG_MANAGER: "PG_MANAGER",
  BROKER: "BROKER",
  INFLUENCER: "INFLUENCER",
  CORPORATE_HR: "CORPORATE_HR",
} as const;

export interface RegisterReferrerBody {
  name: string;
  phone: string;
  persona: RegisterReferrerBodyPersona;
}

export type ReferrerProfilePersona =
  (typeof ReferrerProfilePersona)[keyof typeof ReferrerProfilePersona];

export const ReferrerProfilePersona = {
  EARNER: "EARNER",
  STUDENT: "STUDENT",
  GUARD: "GUARD",
  PG_MANAGER: "PG_MANAGER",
  BROKER: "BROKER",
  INFLUENCER: "INFLUENCER",
  CORPORATE_HR: "CORPORATE_HR",
} as const;

export type ReferrerProfileLevel =
  (typeof ReferrerProfileLevel)[keyof typeof ReferrerProfileLevel];

export const ReferrerProfileLevel = {
  BEGINNER: "BEGINNER",
  EXPLORER: "EXPLORER",
  HUSTLER: "HUSTLER",
  PRO: "PRO",
  LEGEND: "LEGEND",
} as const;

export interface ReferrerProfile {
  id: number;
  name: string;
  phone: string;
  referralCode: string;
  persona: ReferrerProfilePersona;
  totalEarned: number;
  pendingEarnings: number;
  paidEarnings: number;
  xp: number;
  level: ReferrerProfileLevel;
  totalReferrals: number;
  verifiedReferrals: number;
  bookedReferrals: number;
  streak: number;
  /** @nullable */
  teamId?: number | null;
  /** @nullable */
  teamName?: string | null;
  /** @nullable */
  upiId?: string | null;
  createdAt: string;
}

export interface Badge {
  id: string;
  name: string;
  description: string;
  icon: string;
  earnedAt: string;
}

export type ActivityItemType =
  (typeof ActivityItemType)[keyof typeof ActivityItemType];

export const ActivityItemType = {
  REFERRAL_SUBMITTED: "REFERRAL_SUBMITTED",
  LEAD_VERIFIED: "LEAD_VERIFIED",
  LEAD_BOOKED: "LEAD_BOOKED",
  BADGE_EARNED: "BADGE_EARNED",
  LEVEL_UP: "LEVEL_UP",
  CHALLENGE_COMPLETED: "CHALLENGE_COMPLETED",
  TEAM_JOINED: "TEAM_JOINED",
  PROPERTY_LISTED: "PROPERTY_LISTED",
} as const;

export interface ActivityItem {
  id: number;
  type: ActivityItemType;
  description: string;
  /** @nullable */
  amount?: number | null;
  /** @nullable */
  xpGained?: number | null;
  createdAt: string;
}

export interface ReferrerDashboard {
  referrer: ReferrerProfile;
  badges: Badge[];
  nextLevelXp: number;
  currentLevelXp: number;
  recentActivity: ActivityItem[];
  rank: number;
  /** @nullable */
  teamRank?: number | null;
  unreadNotifications: number;
  activeChallenges: number;
}

export interface EarningsDataPoint {
  month: string;
  year: number;
  earned: number;
  referrals: number;
  bookings: number;
}

export type PayoutMethodType =
  (typeof PayoutMethodType)[keyof typeof PayoutMethodType];

export const PayoutMethodType = {
  UPI: "UPI",
  BANK: "BANK",
} as const;

export interface PayoutMethod {
  id: number;
  referrerId: number;
  type: PayoutMethodType;
  /** @nullable */
  upiId?: string | null;
  /** @nullable */
  accountNumber?: string | null;
  /** @nullable */
  ifscCode?: string | null;
  /** @nullable */
  accountName?: string | null;
  isVerified: boolean;
  createdAt: string;
}

export type SetPayoutMethodBodyType =
  (typeof SetPayoutMethodBodyType)[keyof typeof SetPayoutMethodBodyType];

export const SetPayoutMethodBodyType = {
  UPI: "UPI",
  BANK: "BANK",
} as const;

export interface SetPayoutMethodBody {
  type: SetPayoutMethodBodyType;
  upiId?: string;
  accountNumber?: string;
  ifscCode?: string;
  accountName?: string;
}

export type SubmitReferralBodyMoveInTimeline =
  (typeof SubmitReferralBodyMoveInTimeline)[keyof typeof SubmitReferralBodyMoveInTimeline];

export const SubmitReferralBodyMoveInTimeline = {
  IMMEDIATE: "IMMEDIATE",
  WITHIN_WEEK: "WITHIN_WEEK",
  WITHIN_MONTH: "WITHIN_MONTH",
  EXPLORING: "EXPLORING",
} as const;

export type SubmitReferralBodySource =
  (typeof SubmitReferralBodySource)[keyof typeof SubmitReferralBodySource];

export const SubmitReferralBodySource = {
  CUSTOMER: "CUSTOMER",
  OWNER: "OWNER",
  PUBLIC: "PUBLIC",
} as const;

export interface SubmitReferralBody {
  referrerPhone?: string;
  referrerName?: string;
  referralCode?: string;
  leadName: string;
  leadPhone: string;
  moveInTimeline: SubmitReferralBodyMoveInTimeline;
  area?: string;
  source?: SubmitReferralBodySource;
  /**
   * If referring to a specific property
   * @nullable
   */
  propertyId?: number | null;
}

export type ReferralMoveInTimeline =
  (typeof ReferralMoveInTimeline)[keyof typeof ReferralMoveInTimeline];

export const ReferralMoveInTimeline = {
  IMMEDIATE: "IMMEDIATE",
  WITHIN_WEEK: "WITHIN_WEEK",
  WITHIN_MONTH: "WITHIN_MONTH",
  EXPLORING: "EXPLORING",
} as const;

export type ReferralStatus =
  (typeof ReferralStatus)[keyof typeof ReferralStatus];

export const ReferralStatus = {
  NEW: "NEW",
  CONTACTED: "CONTACTED",
  VERIFIED: "VERIFIED",
  MATCHED: "MATCHED",
  VISIT: "VISIT",
  BOOKED: "BOOKED",
  CLOSED: "CLOSED",
  LOST: "LOST",
} as const;

export type ReferralSource =
  (typeof ReferralSource)[keyof typeof ReferralSource];

export const ReferralSource = {
  CUSTOMER: "CUSTOMER",
  OWNER: "OWNER",
  PUBLIC: "PUBLIC",
} as const;

export interface Referral {
  id: number;
  referralId: string;
  /** @nullable */
  referrerId?: number | null;
  /** @nullable */
  referrerName?: string | null;
  leadName: string;
  leadPhone: string;
  moveInTimeline: ReferralMoveInTimeline;
  /** @nullable */
  area?: string | null;
  status: ReferralStatus;
  source: ReferralSource;
  isDuplicate: boolean;
  xpEarned: number;
  createdAt: string;
  updatedAt: string;
}

export type LeaderboardEntryPersona =
  (typeof LeaderboardEntryPersona)[keyof typeof LeaderboardEntryPersona];

export const LeaderboardEntryPersona = {
  EARNER: "EARNER",
  STUDENT: "STUDENT",
  GUARD: "GUARD",
  PG_MANAGER: "PG_MANAGER",
  BROKER: "BROKER",
  INFLUENCER: "INFLUENCER",
  CORPORATE_HR: "CORPORATE_HR",
} as const;

export type LeaderboardEntryLevel =
  (typeof LeaderboardEntryLevel)[keyof typeof LeaderboardEntryLevel];

export const LeaderboardEntryLevel = {
  BEGINNER: "BEGINNER",
  EXPLORER: "EXPLORER",
  HUSTLER: "HUSTLER",
  PRO: "PRO",
  LEGEND: "LEGEND",
} as const;

export interface LeaderboardEntry {
  rank: number;
  referrerId: number;
  name: string;
  persona: LeaderboardEntryPersona;
  level: LeaderboardEntryLevel;
  xp: number;
  totalEarned: number;
  bookedReferrals: number;
  streak: number;
  /** @nullable */
  teamName?: string | null;
}

export interface TeamLeaderboardEntry {
  rank: number;
  teamId: number;
  teamName: string;
  totalXp: number;
  totalEarned: number;
  memberCount: number;
  totalBookings: number;
}

export type PropertyGender =
  (typeof PropertyGender)[keyof typeof PropertyGender];

export const PropertyGender = {
  MALE: "MALE",
  FEMALE: "FEMALE",
  ANY: "ANY",
} as const;

export type PropertyAvailability =
  (typeof PropertyAvailability)[keyof typeof PropertyAvailability];

export const PropertyAvailability = {
  AVAILABLE: "AVAILABLE",
  FULL: "FULL",
  COMING_SOON: "COMING_SOON",
} as const;

export interface Property {
  id: number;
  managerId: number;
  name: string;
  description: string;
  address: string;
  area: string;
  city: string;
  pincode?: string;
  monthlyRent: number;
  deposit: number;
  gender: PropertyGender;
  totalRooms: number;
  availableRooms: number;
  amenities: string[];
  photos: string[];
  availability: PropertyAvailability;
  isVerified: boolean;
  /** @nullable */
  avgRating?: number | null;
  totalReviews: number;
  /** Extra bonus for referrers who send tenants to this PG (above standard ₹500) */
  referralBonus: number;
  /** @nullable */
  nearbyMetro?: string | null;
  /** @nullable */
  nearbyLandmark?: string | null;
  /** @nullable */
  managerName?: string | null;
  /** @nullable */
  managerPhone?: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface Review {
  id: number;
  propertyId: number;
  reviewerName: string;
  /** 1-5 stars */
  rating: number;
  comment: string;
  tags: string[];
  /** @nullable */
  stayDuration?: string | null;
  createdAt: string;
}

export interface PropertyDetail {
  property: Property;
  reviews: Review[];
  nearbyProperties: Property[];
}

export interface PropertiesListResponse {
  properties: Property[];
  total: number;
  offset: number;
  limit: number;
}

export type CreatePropertyBodyGender =
  (typeof CreatePropertyBodyGender)[keyof typeof CreatePropertyBodyGender];

export const CreatePropertyBodyGender = {
  MALE: "MALE",
  FEMALE: "FEMALE",
  ANY: "ANY",
} as const;

export interface CreatePropertyBody {
  managerId: number;
  name: string;
  description: string;
  address: string;
  area: string;
  pincode?: string;
  monthlyRent: number;
  deposit: number;
  gender: CreatePropertyBodyGender;
  totalRooms: number;
  availableRooms: number;
  amenities?: string[];
  nearbyMetro?: string;
  nearbyLandmark?: string;
  referralBonus?: number;
}

export interface UpdatePropertyBody {
  name?: string;
  description?: string;
  address?: string;
  monthlyRent?: number;
  deposit?: number;
  availableRooms?: number;
  amenities?: string[];
  nearbyMetro?: string;
  nearbyLandmark?: string;
  referralBonus?: number;
}

export type UpdatePropertyAvailabilityBodyAvailability =
  (typeof UpdatePropertyAvailabilityBodyAvailability)[keyof typeof UpdatePropertyAvailabilityBodyAvailability];

export const UpdatePropertyAvailabilityBodyAvailability = {
  AVAILABLE: "AVAILABLE",
  FULL: "FULL",
  COMING_SOON: "COMING_SOON",
} as const;

export interface UpdatePropertyAvailabilityBody {
  availability: UpdatePropertyAvailabilityBodyAvailability;
  availableRooms?: number;
}

export interface AddReviewBody {
  reviewerName: string;
  reviewerPhone?: string;
  rating: number;
  comment: string;
  tags?: string[];
  stayDuration?: string;
}

export interface ManagerStats {
  totalProperties: number;
  totalRooms: number;
  occupiedRooms: number;
  occupancyRate: number;
  totalLeadsReceived: number;
  totalBookings: number;
  conversionRate: number;
  monthlyRevenue: number;
  /** @nullable */
  avgRating?: number | null;
  overflowLeadsThisMonth: number;
  referralEarnings: number;
}

export interface OverflowLead {
  id: number;
  leadName: string;
  moveInTimeline: string;
  area: string;
  status: string;
  referredAt: string;
  suggestedProperties: Property[];
}

export interface Team {
  id: number;
  name: string;
  description: string;
  captainId: number;
  captainName: string;
  inviteCode: string;
  memberCount: number;
  totalXp: number;
  totalEarned: number;
  totalBookings: number;
  createdAt: string;
}

export type TeamMemberPersona =
  (typeof TeamMemberPersona)[keyof typeof TeamMemberPersona];

export const TeamMemberPersona = {
  EARNER: "EARNER",
  STUDENT: "STUDENT",
  GUARD: "GUARD",
  PG_MANAGER: "PG_MANAGER",
  BROKER: "BROKER",
  INFLUENCER: "INFLUENCER",
  CORPORATE_HR: "CORPORATE_HR",
} as const;

export type TeamMemberLevel =
  (typeof TeamMemberLevel)[keyof typeof TeamMemberLevel];

export const TeamMemberLevel = {
  BEGINNER: "BEGINNER",
  EXPLORER: "EXPLORER",
  HUSTLER: "HUSTLER",
  PRO: "PRO",
  LEGEND: "LEGEND",
} as const;

export interface TeamMember {
  referrerId: number;
  name: string;
  persona: TeamMemberPersona;
  level: TeamMemberLevel;
  xp: number;
  /** XP contributed to team */
  contribution: number;
  isCaptain: boolean;
  joinedAt: string;
}

export interface TeamDetail {
  team: Team;
  members: TeamMember[];
  recentActivity: ActivityItem[];
}

export interface CreateTeamBody {
  name: string;
  description?: string;
  captainId: number;
}

export interface JoinTeamBody {
  referrerId: number;
  inviteCode: string;
}

export interface LeaveTeamBody {
  referrerId: number;
}

export type ChallengeType = (typeof ChallengeType)[keyof typeof ChallengeType];

export const ChallengeType = {
  DAILY: "DAILY",
  WEEKLY: "WEEKLY",
  MILESTONE: "MILESTONE",
  SPECIAL: "SPECIAL",
} as const;

export interface Challenge {
  id: number;
  title: string;
  description: string;
  type: ChallengeType;
  xpReward: number;
  bonusAmount: number;
  target: number;
  /** referrals, bookings, streak_days, etc. */
  unit: string;
  expiresAt?: string;
  isCompleted: boolean;
  progress: number;
  icon: string;
}

export interface CompleteChallengeBody {
  referrerId: number;
}

export interface ChallengeCompletion {
  challengeId: number;
  referrerId: number;
  xpEarned: number;
  bonusEarned: number;
  /** @nullable */
  newLevel?: string | null;
  completedAt: string;
}

export type NotificationType =
  (typeof NotificationType)[keyof typeof NotificationType];

export const NotificationType = {
  LEAD_VERIFIED: "LEAD_VERIFIED",
  LEAD_BOOKED: "LEAD_BOOKED",
  PAYOUT_APPROVED: "PAYOUT_APPROVED",
  PAYOUT_PAID: "PAYOUT_PAID",
  LEVEL_UP: "LEVEL_UP",
  BADGE_EARNED: "BADGE_EARNED",
  CHALLENGE_COMPLETED: "CHALLENGE_COMPLETED",
  TEAM_INVITE: "TEAM_INVITE",
  PROPERTY_VERIFIED: "PROPERTY_VERIFIED",
  OVERFLOW_LEAD: "OVERFLOW_LEAD",
} as const;

export interface Notification {
  id: number;
  referrerId: number;
  type: NotificationType;
  title: string;
  message: string;
  /** @nullable */
  amount?: number | null;
  isRead: boolean;
  createdAt: string;
}

export interface AreaStat {
  name: string;
  slug: string;
  totalPGs: number;
  availablePGs: number;
  avgRent: number;
  totalLeads: number;
  popularityScore: number;
  description: string;
  metroNearby: string;
}

export type EarningsEstimateEstimatedLevel =
  (typeof EarningsEstimateEstimatedLevel)[keyof typeof EarningsEstimateEstimatedLevel];

export const EarningsEstimateEstimatedLevel = {
  BEGINNER: "BEGINNER",
  EXPLORER: "EXPLORER",
  HUSTLER: "HUSTLER",
  PRO: "PRO",
  LEGEND: "LEGEND",
} as const;

export interface EarningsEstimate {
  referrals: number;
  verifiedCount: number;
  bookedCount: number;
  verificationEarnings: number;
  bookingEarnings: number;
  totalEarnings: number;
  xpEarned: number;
  estimatedLevel: EarningsEstimateEstimatedLevel;
  monthlyProjection: number;
}

export type LeadStatus = (typeof LeadStatus)[keyof typeof LeadStatus];

export const LeadStatus = {
  NEW: "NEW",
  CONTACTED: "CONTACTED",
  VERIFIED: "VERIFIED",
  MATCHED: "MATCHED",
  VISIT: "VISIT",
  BOOKED: "BOOKED",
  CLOSED: "CLOSED",
  LOST: "LOST",
} as const;

export interface Lead {
  id: number;
  referralId: string;
  leadName: string;
  leadPhone: string;
  moveInTimeline: string;
  /** @nullable */
  area?: string | null;
  status: LeadStatus;
  source: string;
  /** @nullable */
  referrerName?: string | null;
  /** @nullable */
  assignedAgentName?: string | null;
  isDuplicate: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface LeadsListResponse {
  leads: Lead[];
  total: number;
  offset: number;
  limit: number;
}

export type LeadDetailStatus =
  (typeof LeadDetailStatus)[keyof typeof LeadDetailStatus];

export const LeadDetailStatus = {
  NEW: "NEW",
  CONTACTED: "CONTACTED",
  VERIFIED: "VERIFIED",
  MATCHED: "MATCHED",
  VISIT: "VISIT",
  BOOKED: "BOOKED",
  CLOSED: "CLOSED",
  LOST: "LOST",
} as const;

export type LeadNoteType = (typeof LeadNoteType)[keyof typeof LeadNoteType];

export const LeadNoteType = {
  CALL_LOG: "CALL_LOG",
  NOTE: "NOTE",
  STATUS_CHANGE: "STATUS_CHANGE",
} as const;

export interface LeadNote {
  id: number;
  leadId: number;
  note: string;
  type: LeadNoteType;
  createdByName: string;
  createdAt: string;
}

export interface LeadTimelineEvent {
  status: string;
  timestamp: string;
  /** @nullable */
  note?: string | null;
}

export interface LeadDetail {
  id: number;
  referralId: string;
  leadName: string;
  leadPhone: string;
  moveInTimeline: string;
  /** @nullable */
  area?: string | null;
  status: LeadDetailStatus;
  source: string;
  /** @nullable */
  referrerId?: number | null;
  /** @nullable */
  referrerName?: string | null;
  /** @nullable */
  referrerPhone?: string | null;
  /** @nullable */
  assignedAgentId?: number | null;
  /** @nullable */
  assignedAgentName?: string | null;
  isDuplicate: boolean;
  notes: LeadNote[];
  timeline: LeadTimelineEvent[];
  createdAt: string;
  updatedAt: string;
}

export type UpdateLeadStatusBodyStatus =
  (typeof UpdateLeadStatusBodyStatus)[keyof typeof UpdateLeadStatusBodyStatus];

export const UpdateLeadStatusBodyStatus = {
  NEW: "NEW",
  CONTACTED: "CONTACTED",
  VERIFIED: "VERIFIED",
  MATCHED: "MATCHED",
  VISIT: "VISIT",
  BOOKED: "BOOKED",
  CLOSED: "CLOSED",
  LOST: "LOST",
} as const;

export interface UpdateLeadStatusBody {
  status: UpdateLeadStatusBodyStatus;
  note?: string;
  assignedAgentId?: number;
}

export type AddLeadNoteBodyType =
  (typeof AddLeadNoteBodyType)[keyof typeof AddLeadNoteBodyType];

export const AddLeadNoteBodyType = {
  CALL_LOG: "CALL_LOG",
  NOTE: "NOTE",
} as const;

export interface AddLeadNoteBody {
  note: string;
  type: AddLeadNoteBodyType;
  agentName: string;
}

export type PayoutType = (typeof PayoutType)[keyof typeof PayoutType];

export const PayoutType = {
  VERIFICATION_BONUS: "VERIFICATION_BONUS",
  BOOKING_BONUS: "BOOKING_BONUS",
} as const;

export type PayoutStatus = (typeof PayoutStatus)[keyof typeof PayoutStatus];

export const PayoutStatus = {
  PENDING: "PENDING",
  APPROVED: "APPROVED",
  PAID: "PAID",
} as const;

export interface Payout {
  id: number;
  referrerId: number;
  referrerName: string;
  referrerPhone: string;
  amount: number;
  type: PayoutType;
  status: PayoutStatus;
  referralId: string;
  leadName: string;
  createdAt: string;
  /** @nullable */
  paidAt?: string | null;
}

export interface StatusCount {
  status: string;
  count: number;
}

export interface SourceCount {
  source: string;
  count: number;
}

export interface AnalyticsSummary {
  totalLeads: number;
  verifiedLeads: number;
  bookedLeads: number;
  lostLeads: number;
  conversionRate: number;
  totalPayoutLiability: number;
  totalRevenue: number;
  totalReferrers: number;
  activeReferrers: number;
  totalProperties: number;
  leadsByStatus: StatusCount[];
  leadsBySource: SourceCount[];
  recentLeads: Lead[];
  topEarners: LeaderboardEntry[];
}

export interface Agent {
  id: number;
  name: string;
  phone: string;
  activeLeads: number;
  totalClosed: number;
}

export type GetLeaderboardParams = {
  limit?: number;
  period?: GetLeaderboardPeriod;
};

export type GetLeaderboardPeriod =
  (typeof GetLeaderboardPeriod)[keyof typeof GetLeaderboardPeriod];

export const GetLeaderboardPeriod = {
  all_time: "all_time",
  monthly: "monthly",
  weekly: "weekly",
} as const;

export type GetTeamLeaderboardParams = {
  limit?: number;
};

export type GetPropertiesParams = {
  area?: string;
  minPrice?: number;
  maxPrice?: number;
  gender?: GetPropertiesGender;
  /**
   * Comma-separated amenity list
   */
  amenities?: string;
  availability?: GetPropertiesAvailability;
  limit?: number;
  offset?: number;
};

export type GetPropertiesGender =
  (typeof GetPropertiesGender)[keyof typeof GetPropertiesGender];

export const GetPropertiesGender = {
  MALE: "MALE",
  FEMALE: "FEMALE",
  ANY: "ANY",
} as const;

export type GetPropertiesAvailability =
  (typeof GetPropertiesAvailability)[keyof typeof GetPropertiesAvailability];

export const GetPropertiesAvailability = {
  AVAILABLE: "AVAILABLE",
  FULL: "FULL",
  ANY: "ANY",
} as const;

export type GetChallengesParams = {
  referrerId?: number;
};

export type GetNotificationsParams = {
  unreadOnly?: boolean;
};

export type CalculateEarningsParams = {
  referrals?: number;
  verifyRate?: number;
  bookRate?: number;
};

export type AdminGetLeadsParams = {
  status?: AdminGetLeadsStatus;
  assignedTo?: number;
  limit?: number;
  offset?: number;
};

export type AdminGetLeadsStatus =
  (typeof AdminGetLeadsStatus)[keyof typeof AdminGetLeadsStatus];

export const AdminGetLeadsStatus = {
  NEW: "NEW",
  CONTACTED: "CONTACTED",
  VERIFIED: "VERIFIED",
  MATCHED: "MATCHED",
  VISIT: "VISIT",
  BOOKED: "BOOKED",
  CLOSED: "CLOSED",
  LOST: "LOST",
} as const;

export type AdminGetPayoutsParams = {
  status?: AdminGetPayoutsStatus;
};

export type AdminGetPayoutsStatus =
  (typeof AdminGetPayoutsStatus)[keyof typeof AdminGetPayoutsStatus];

export const AdminGetPayoutsStatus = {
  PENDING: "PENDING",
  APPROVED: "APPROVED",
  PAID: "PAID",
} as const;
